<script setup lang="ts">
import { useRouter } from "vue-router";

const router = useRouter();

const features = [
  {
    icon: "🎯",
    title: "Personalised Scoring",
    description:
      "Our weighted algorithm evaluates budget fit, use-case match, feature alignment, safety, and efficiency — all transparently.",
  },
  {
    icon: "🤖",
    title: "Gemini AI Narration",
    description:
      "Each recommendation comes with a natural-language explanation generated by Google Gemini, with a deterministic fallback.",
  },
  {
    icon: "⚡",
    title: "Side-by-Side Compare",
    description:
      "Pick up to 4 cars and compare specs, safety stars, price, mileage, and more in a clean comparison table.",
  },
];

const stats = [
  { value: "50+", label: "Cars catalogued" },
  { value: "6", label: "Body segments" },
  { value: "5", label: "Fuel types" },
  { value: "100%", label: "Transparent scores" },
];

function goToQuestionnaire() {
  void router.push({ name: "questionnaire" });
}

function goToBrowse() {
  void router.push({ name: "browse" });
}
</script>

<template>
  <div class="relative overflow-hidden">
    <!-- Ambient glow -->
    <div
      class="pointer-events-none absolute inset-0 -z-10"
      aria-hidden="true"
    >
      <div class="absolute left-1/4 top-0 h-[600px] w-[600px] -translate-x-1/2 rounded-full bg-amber-500/10 blur-[120px]" />
      <div class="absolute right-0 top-1/4 h-[400px] w-[400px] rounded-full bg-orange-600/8 blur-[100px]" />
    </div>

    <!-- Hero Section -->
    <section class="mx-auto flex min-h-[calc(100vh-73px)] max-w-6xl flex-col items-center justify-center px-6 py-20 text-center">
      <p class="mb-4 text-sm font-medium uppercase tracking-[0.3em] text-amber-400">
        Indian Car Discovery Platform
      </p>

      <h1 class="mb-6 text-5xl font-bold leading-tight tracking-tight text-stone-50 md:text-7xl">
        Find your
        <span class="bg-gradient-to-r from-amber-300 to-orange-400 bg-clip-text text-transparent">perfect car</span>
        <br>in minutes.
      </h1>

      <p class="mb-10 max-w-2xl text-lg text-stone-400 md:text-xl">
        Answer a few questions about your lifestyle, budget, and preferences. Our AI-powered scoring
        engine ranks every car that's right for you — with a detailed breakdown.
      </p>

      <div class="flex flex-wrap items-center justify-center gap-4">
        <button
          id="cta-start-questionnaire"
          class="rounded-2xl bg-gradient-to-r from-amber-400 to-orange-400 px-8 py-4 text-base font-semibold text-stone-950 shadow-lg shadow-amber-500/30 transition hover:scale-105 hover:shadow-amber-500/50 active:scale-95"
          @click="goToQuestionnaire"
        >
          Get Recommendations →
        </button>
        <button
          id="cta-browse-cars"
          class="rounded-2xl border border-stone-700 bg-stone-800/60 px-8 py-4 text-base font-semibold text-stone-200 transition hover:border-stone-600 hover:bg-stone-700/60 active:scale-95"
          @click="goToBrowse"
        >
          Browse All Cars
        </button>
      </div>
    </section>

    <!-- Feature cards -->
    <section class="mx-auto max-w-6xl px-6 pb-24">
      <div class="grid gap-6 md:grid-cols-3">
        <div
          v-for="feature in features"
          :key="feature.title"
          class="rounded-3xl border border-stone-800 bg-stone-900/60 p-6 transition hover:border-stone-700"
        >
          <div class="mb-4 text-3xl">
            {{ feature.icon }}
          </div>
          <h3 class="mb-2 text-lg font-semibold text-stone-100">
            {{ feature.title }}
          </h3>
          <p class="text-sm leading-relaxed text-stone-400">
            {{ feature.description }}
          </p>
        </div>
      </div>
    </section>

    <!-- Stats band -->
    <section class="border-y border-stone-800 bg-stone-900/40 py-10">
      <div class="mx-auto grid max-w-4xl grid-cols-2 gap-8 px-6 text-center md:grid-cols-4">
        <div
          v-for="stat in stats"
          :key="stat.label"
        >
          <p class="text-3xl font-bold text-amber-400">
            {{ stat.value }}
          </p>
          <p class="mt-1 text-sm text-stone-400">
            {{ stat.label }}
          </p>
        </div>
      </div>
    </section>
  </div>
</template>
